### ISSUE TITLE
Bot cannot detect Large Stumps, Large Logs, Buildings

### ISSUE THREAD

**Issue by tiansh** [JoeStrout/Farmtronics#6]
What happened:

* bot may pass through a Large Stumps, Large Logs, Buildings
* `bot.ahead` or `farm.tile` returns null for these tiles.

![Game screenshot](https://user-images.githubusercontent.com/6500326/151989127-7fc6b944-3568-4386-8d9a-fcadeb13fb8a.PNG)

Expected:

Bot should be blocked by Large Stumps, Large Logs, Buildings. `farm.tile` should return something meaningful or some other API should be added.

**Comment by JoeStrout** [comment]
Yes, this was a mistake in the most recent update.  We'll get it fixed for the next one.  Thank yo ufor reporting it!

**Comment by JoeStrout** [comment]
Fixed 1.0.6.

**Comment by tiansh** [comment]
I had tried to checked out codes on main branch. Hollow Logs, Stumps, and, Boulders can be detected correctly now. But the bot `farm.tile` still doesn't give any information about buildings or any map borders.

![`bot.ahead` returns null](https://user-images.githubusercontent.com/6500326/152116492-3792e637-8a53-4f8a-9d47-26d6da57e673.PNG)

**Comment by tiansh** [comment]
I would suggest to redesign the tile info object to include more data...

1. There may be multiple items in a single tile. Maybe tile info may be split into multiple parts, including a list of items on the tile, and some basic information of the tile.
    * `farm.tile` only reports 1 item per tile. There may be multiple items placed on the tile. And if so, only the top one is reported. A tile may contains multiple items for example: place a chest on a flooring, place a bot on a plant...
2. Some property of tile may be interested by a bot. And these info may be hard to obtain under current API. Add them as a property of tile may solve the problem.
    * If bot may plant crops / trees on the tile;
    * If the tile may be used to refill water can, may fish on the tile;
    * If the bot may move onto / pass the tile
3. Crops may need more property
    * Is the crop had been watered today;

**Comment by JoeStrout** [comment]
You're right that there may be multiple things to report, but I'm trying to keep it simple for the user by only reporting the top or most important thing.

The last release reports a lot more info, but yes, there are still things it misses.  This data in SDV itself is scattered over many different places and harder to gather than one might expect.  But we'll keep improving it.

Note that you can already tell if a crop (or any HoeDirt) has been watered or not.
